<a href="https://colab.research.google.com/github/ashishkumarblog6783-code/HumanResourceManagementSystem/blob/main/numy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
%time [j**4 for j in range(1,9)]

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 11.2 µs


[1, 16, 81, 256, 625, 1296, 2401, 4096]

In [2]:
%timeit np.arange(1,9)**4

2.01 µs ± 60.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
import numpy as np
x=[1,2,3,4,5]
y=np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [6]:
l=[]
for i in range(1,5):
  int_1=input("enter")
  l.append(int_1)
print(np.array(l))

enter12
enter45
enter67
enter78
['12' '45' '67' '78']


In [10]:
ar2=np.array([[1,2,3],[5,6,7]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [5 6 7]]
2


In [15]:
ar3=np.array([[[2,3,4,5,5],[7,3,4,5,6],[6,5,6,7,8]]])
print(ar3)
print(ar3.ndim)

[[[2 3 4 5 5]
  [7 3 4 5 6]
  [6 5 6 7 8]]]
3


In [19]:
zero=np.zeros(5)
zero1=np.zeros((3,5))
print(zero)
print(zero1)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
one=np.ones(7)
one1=np.zeros((4,6))
print(one)
print(one1)

[1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
arr=np.arange(4)
print(arr)

[0 1 2 3]


In [24]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr=np.eye(3,6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [27]:
arr=np.linspace(1,10,num=3)
print(arr)

[ 1.   5.5 10. ]


In [28]:
import numpy as np
var=np.random.rand(4)
print(var)

[0.80805688 0.62496545 0.23551801 0.38005119]


In [29]:
var1=np.random.rand(2,5)
print(var1)

[[0.68229249 0.50236825 0.12466462 0.31196685 0.63968409]
 [0.18169058 0.92797238 0.05208616 0.16812193 0.20397932]]


In [30]:
var2=np.random.randn(5)
print(var2)

[-0.75184545  1.4530167   0.25037258  1.50930947 -0.11935408]


In [31]:
var3=np.random.ranf(5)
print(var3)

[0.26190997 0.6367194  0.2683549  0.94475889 0.61186056]


In [34]:
var4=np.random.randint(6,26,4)
print(var4)

[17 11 18 25]


In [35]:
 import numpy as np
 var=np.array([1,2,3,4,5])
 print("data type",var.dtype)

data type int64


In [37]:
import numpy as np
var=np.array([33.87,7,9])
print(var.dtype)


float64


In [40]:
import numpy as np
var2=np.array(["jhdbfjbjdh","jjf","ururu"])
print(var2.dtype)

<U10


In [43]:
x=np.array([1,2,3,4],dtype=np.int32)
print(x)
print(x.dtype)

[1 2 3 4]
int32


In [49]:
import numpy as np
ar=np.array([1,2,3,4,5])
add=ar+3
print(add)

[4 5 6 7 8]


In [51]:
ar=np.array([1,2,3,4,5])
div=ar/4
print(div)

[0.25 0.5  0.75 1.   1.25]


In [52]:
var1=np.array([[4,7,9,0,6],[5,7,1,2,8]])
var2=np.array([[1,2,3,4,5],[5,6,7,8,9]])
varadd=var1+var2
print(varadd)

[[ 5  9 12  4 11]
 [10 13  8 10 17]]
